### ISSUE TITLE
Hello, can you give me a packaged folder for this data set?

### ISSUE THREAD

**Issue by Blairxyc** [Yueeeeeeee/CANMD#1]
Hello, can you give me a packaged folder for this data set?

**Comment by Yueeeeeeee** [comment]
Shared dataset

**Comment by Blairxyc** [comment]
![image](https://github.com/Yueeeeeeee/CANMD/assets/96876583/ef2d3eff-ef27-4b91-8067-90dc492c0973)

ANTiVax can not get dataset.csv file, it only has label and id details, but not content (text) information, could you please give an additional link?
